<?php

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_help().
 */
function taxonomy_batch_add_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.taxonomy_batch_add':
      return '<p>' . t('A module to batch add taxonomy terms.') . '</p>';
  }
}

/**
 * Batch process callback to add taxonomy terms.
 */
function taxonomy_batch_add_process_term($term_data, &$context) {
  $vocabulary_id = $term_data['vocabulary'];
  $term_name = $term_data['name'];

  if (!empty($term_name)) {
    $term = Term::create([
      'name' => $term_name,
      'vid' => $vocabulary_id,
    ]);
    $term->save();
    $context['message'] = t('Added term: @term', ['@term' => $term_name]);
  }
}

/**
 * Batch finished callback to display a summary.
 */
function taxonomy_batch_add_finished($success, array $results, array $operations) {
    $message = $success 
      ? t('@added_terms terms were added successfully. @duplicates terms were duplicates and were not added.', [
          '@added_terms' => $results['added_terms_count'],
          '@duplicates' => $results['duplicates_count'],
        ])
      : t('An error occurred while adding terms.');
  
    \Drupal::messenger()->addMessage($message);
  }
  